D:\ComputerScience\CODES\MatPlotAgent-main\workspace\example_4\code_action_gpt-4o_initial_2.py:12: RuntimeWarning: covariance is not symmetric positive-semidefinite.
  data = np.random.multivariate_normal(mean, cov, 700)
D:\ComputerScience\CODES\MatPlotAgent-main\workspace\example_4\code_action_gpt-4o_initial_2.py:26: RuntimeWarning: invalid value encountered in sqrt
  ell_radius_y = np.sqrt(1 - pearson)
Traceback (most recent call last):
  File "D:\ComputerScience\CODES\MatPlotAgent-main\workspace\example_4\code_action_gpt-4o_initial_2.py", line 36, in <module>
    plot_confidence_ellipse(ax, mean, cov, 1, edgecolor='firebrick', linestyle='-')
  File "D:\ComputerScience\CODES\MatPlotAgent-main\workspace\example_4\code_action_gpt-4o_initial_2.py", line 30, in plot_confidence_ellipse
    transf = plt.transforms.Affine2D().rotate_deg(45).scale(scale_x, scale_y).translate(mean[0], mean[1])
AttributeError: module 'matplotlib.pyplot' has no attribute 'transforms'
